### ISSUE TITLE
Question on skipping objects

### ISSUE THREAD

**Issue by JonasKuschel** [acse-ci223/bambulabs_api#43]
Is it possible to skip objects when this api is used? We are currently using the Bigtree tech Panda Touch and when we send print jobs from it, it is not possible to skip individual objects via App or Computer. Is it the same with this api?

**Comment by acse-ci223** [comment]
From a quick investigation, it looks like ``skip_objects`` is an entry in the MQTT report. So theoretically it might be possible to skip objects. We'll look into it.
